name: wazzi
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  bubble_bottom_bar: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_zoom_drawer: ^3.0.1
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  line_awesome_flutter: ^2.0.0
  firebase_storage: ^11.0.3
  geolocator: ^10.1.0
  provider: ^6.0.2
  multi_select_flutter: ^4.1.2
  bottom_navy_bar: ^6.0.0
  hexcolor: ^3.0.1
  http: ^1.1.0
  fluttertoast: ^8.1.2
  google_maps_flutter: ^2.5.3
  cloud_firestore: ^4.15.1
  pinput: ^4.0.0
  permission_handler: ^11.0.1
  flutter_spinkit: ^5.1.0
  firebase_auth: ^4.17.4
  app_settings: ^5.1.1
  share_plus: ^7.2.2
  geocoding: ^2.1.1
  
 
  

dev_dependencies:
  

  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.3.10  
  flutter_lints: ^3.0.0
  
flutter_native_splash:
  color: "#f7f6f1"
  image: images/waaz.png
  android: true
  ios: true


 
  
  

  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - images/diagnostics.jpg
      - images/waazi.png
      - images/machanics.jpg
      - images/diagnostic.png
      - images/tows.png
      - images/waaz.png
      - images/slider.png
      - images/repairs.png
      - images/services.png
      - images/oil.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

 
  # example:
  #fonts:
    #- family: Schyler
      #fonts:
       # - asset: fonts/Schyler-Regular.ttf
       #- asset: fonts/Schyler-Italic.ttf
       #   style: italic
    #- family: Trajan Pro
     # fonts:
       # - asset: fonts/TrajanPro.ttf
       # - asset: fonts/TrajanPro_Bold.ttf
       #   weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
